import React from 'react';

export interface SvgIconProps {
  size?: number;
  fillColor?: string;
  style?: React.CSSProperties;
}

export * from './generated/ArrowDown';
export * from './generated/ArrowDownCircle';
export * from './generated/ArrowExpand';
export * from './generated/ArrowLeft';
export * from './generated/ArrowLeftCircle';
export * from './generated/ArrowRight';
export * from './generated/ArrowRightCircle';
export * from './generated/ArrowShrink';
export * from './generated/ArrowUp';
export * from './generated/ArrowUpCircle';
export * from './generated/Camera';
export * from './generated/CameraSquare';
export * from './generated/CaretDownMedium';
export * from './generated/CaretDownSmall';
export * from './generated/CaretLeftMedium';
export * from './generated/CaretLeftSmall';
export * from './generated/CaretRightMedium';
export * from './generated/CaretRightSmall';
export * from './generated/CaretUpMedium';
export * from './generated/CaretUpSmall';
export * from './generated/Character';
export * from './generated/CheckSquare';
export * from './generated/CheckSquareChecked';
export * from './generated/ChevronDown';
export * from './generated/ChevronLeft';
export * from './generated/ChevronRight';
export * from './generated/ChevronUp';
export * from './generated/Close';
export * from './generated/Cursor';
export * from './generated/CursorSquare';
export * from './generated/DopeSheet';
export * from './generated/DopeSheetSquare';
export * from './generated/FastForward';
export * from './generated/FastRewind';
export * from './generated/Folder';
export * from './generated/Hand';
export * from './generated/HandSquare';
export * from './generated/Hide';
export * from './generated/Iconview';
export * from './generated/Image';
export * from './generated/Listview';
export * from './generated/Lock';
export * from './generated/LockSmall';
export * from './generated/MagnifyingGlass';
export * from './generated/MagnifyingGlassSquare';
export * from './generated/Pause';
export * from './generated/PlayArrow';
export * from './generated/Plus';
export * from './generated/Record';
export * from './generated/Search';
export * from './generated/Setting';
export * from './generated/Show';
export * from './generated/UnfoldLess';
export * from './generated/UnfoldMore';
export * from './generated/Unlock';
export * from './generated/UnlockSmall';